"""empty message

Revision ID: 37ccd417bd46
Revises: da2ef9ec7f43
Create Date: 2023-10-03 22:07:49.702580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ccd417bd46'
down_revision = 'da2ef9ec7f43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productOrder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'customer', ['cust_id'], ['cust_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productOrder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cust_id')

    # ### end Alembic commands ###
