"""empty message

Revision ID: 472d02df046b
Revises: 
Create Date: 2023-09-29 12:45:42.104972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472d02df046b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('order_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('product',
    sa.Column('prod_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('prod_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('fname', sa.Text(), nullable=True),
    sa.Column('lname', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('pwd', sa.Text(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('productOrder',
    sa.Column('prodorder_id', sa.String(), nullable=False),
    sa.Column('prod_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['prod_id'], ['product.prod_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('prodorder_id')
    )
    op.create_table('property',
    sa.Column('prop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('purch_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('est_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('_user_id', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('roi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['_user_id'], ['users.user_id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('prop_id')
    )
    op.create_table('expense',
    sa.Column('inc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prop_id'], ['property.prop_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('inc_id')
    )
    op.create_table('income',
    sa.Column('inc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prop_id'], ['property.prop_id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('inc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    op.drop_table('expense')
    op.drop_table('property')
    op.drop_table('productOrder')
    op.drop_table('users')
    op.drop_table('product')
    op.drop_table('order')
    # ### end Alembic commands ###
