"""empty message

Revision ID: 987c5c48745e
Revises: 7bd1adcd9ae4
Create Date: 2023-10-08 07:14:26.152151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987c5c48745e'
down_revision = '7bd1adcd9ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productOrder', schema=None) as batch_op:
        batch_op.alter_column('cust_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_me')
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    with op.batch_alter_table('productOrder', schema=None) as batch_op:
        batch_op.alter_column('cust_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
